stuff

diff --git a/home/bin/usb b/home/bin/usb
--- a/home/bin/usb
+++ b/home/bin/usb
@@ -2,11 +2,11 @@
 
 the_usage() {
 	this=${0##*/}
-	echo -e "$this: usage:"
-	echo -e "\t$this ls TO list (removable) devices"
-	echo -e "\t$this mount DEVICE TO mount a device"
-	echo -e "\t$this eject DEVICE TO eject a device"
-	echo -e "\t$this open DEVICE TO mount a device, open it in the SHELL, and then eject"
+	echo "$this: usage:"
+	echo "    $this ls TO list (removable) devices"
+	echo "    $this mount DEVICE TO mount a device"
+	echo "    $this eject DEVICE TO eject a device"
+	echo "    $this open DEVICE TO mount a device, open it in the SHELL, and then eject"
 }
 
 usage() {
@@ -15,7 +15,7 @@ usage() {
 }
 
 usb_check() {
-	[ "$(lsblk -drno TYPE $1)" = part ] && [ "$(lsblk -drno RM $1)" = 1 ]
+	[ "$(lsblk -drno TYPE "$1")" = part ] && [ "$(lsblk -drno RM "$1")" = 1 ]
 }
 
 
@@ -37,11 +37,11 @@ usb_list() {
 
 usb_check_critical() {
 	if ! [ -b "$1" ]; then
-		echo -e "$1 is not a block device"
+		echo "$1 is not a block device"
 		exit 1
 	fi
 	if ! usb_check "$1"; then
-		echo -e "$1 is not a removable partition"
+		echo "$1 is not a removable partition"
 		exit 1
 	fi
 }
@@ -51,7 +51,7 @@ usb_mount() {
 
 	usb_check_critical "$part"
 
-	udisksctl mount -b $part
+	udisksctl mount -b "$part" || { echo "Failed to mount $part"; return 1; }
 }
 
 usb_eject() {
@@ -59,24 +59,24 @@ usb_eject() {
 
 	usb_check_critical "$part"
 
-	disk=$(readlink /sys/class/block/${part#/dev/})
+	disk=$(readlink "/sys/class/block/${part#/dev/}")
 	disk=${disk%/*}
 	disk=/dev/${disk##*/}
 
-	udisksctl unmount -b $part
-	udisksctl power-off -b $disk
+	udisksctl unmount -b "$part" || { echo "Failed to unmount $part"; return 1; }
+	udisksctl power-off -b "$disk" || { echo "Failed to power-off $disk"; return 1; }
 }
 
 usb_open() {
-	usb_mount "$1"
+	usb_mount "$1" || exit 1
 
-	mpoint=$(lsblk -no mountpoint /dev/${1#/dev/})
-	olddir=$PWD
-	cd $mpoint
-	$SHELL
-	cd $olddir
+	mpoint="$(lsblk -no mountpoint "/dev/${1#/dev/}")"
+	olddir="$PWD"
+	cd "$mpoint" || { usb_eject "$1"; exit 1; }
+	$SHELL || { usb_eject "$1"; exit 1; }
+	cd "$olddir" || { usb_eject "$1"; exit 1; }
 
-	usb_eject "$1"
+	usb_eject "$1" || exit 1
 }
 
 ############################
@@ -87,7 +87,7 @@ arg=$2
 if [ -z "$opt" ]; then
 	usage
 fi
-if [ $opt != ls ] && [ -z "$arg" ]; then
+if [ "$opt" != ls ] && [ -z "$arg" ]; then
 	usage
 fi
 
